export const MOCK_PROJECTS = [
  {
    id: '1',
    building_id: 'BLD001',
    building_type: 'Residential',
    name: 'Ramesh Sharma',
    mobile: '9876543210',
    email: 'ramesh@example.com',
    address: '42, Green Park Extension, New Delhi - 110016',
    landmark: 'Near Hauz Khas Metro',
    assigned_member: 'Arjun Mehta',
    description: 'Luxury 4BHK residential bungalow',
    okas_box_info: 'OKS-2024-001',
  },
  {
    id: '2',
    building_id: 'BLD002',
    building_type: 'Commercial',
    name: 'Priya Kapoor',
    mobile: '8765432109',
    email: 'priya@example.com',
    address: 'Plot 12, Cyber City, Gurugram - 122002',
    landmark: 'DLF Cyber Park',
    assigned_member: 'Sneha Patel',
    description: 'Corporate office automation',
    okas_box_info: 'OKS-2024-002',
  },
  {
    id: '3',
    building_id: 'BLD003',
    building_type: 'Residential',
    name: 'Vikram Joshi',
    mobile: '7654321098',
    email: 'vikram@example.com',
    address: '15, Palm Beach Road, Mumbai - 400706',
    landmark: 'Near Palm Beach Metro',
    assigned_member: 'Arjun Mehta',
    description: 'Sea-facing penthouse automation',
    okas_box_info: 'OKS-2024-003',
  },
  {
    id: '4',
    building_id: 'BLD004',
    building_type: 'Industrial',
    name: 'Anita Reddy',
    mobile: '6543210987',
    email: 'anita@example.com',
    address: 'Survey No. 45, MIDC Phase 2, Pune - 411019',
    landmark: 'MIDC Industrial Area',
    assigned_member: 'Rohan Desai',
    description: 'Factory floor lighting control',
    okas_box_info: 'OKS-2024-004',
  },
  {
    id: '5',
    building_id: 'BLD005',
    building_type: 'Non business',
    name: 'Suresh Nair',
    mobile: '9988776655',
    email: 'suresh@example.com',
    address: 'Temple Road, Thiruvananthapuram - 695001',
    landmark: 'Near Padmanabhaswamy Temple',
    assigned_member: 'Sneha Patel',
    description: 'Heritage building smart controls',
    okas_box_info: 'OKS-2024-005',
  },
];

export const MOCK_MEMBERS = [
  { id: '1', full_name: 'Arjun Mehta',  email: 'arjun@okas.one',  mobile: '9876543210', role: 'Admin',  status: 'Active' },
  { id: '2', full_name: 'Sneha Patel',  email: 'sneha@okas.one',  mobile: '8765432109', role: 'Member', status: 'Active' },
  { id: '3', full_name: 'Rohan Desai',  email: 'rohan@okas.one',  mobile: '7654321098', role: 'Member', status: 'Active' },
  { id: '4', full_name: 'Meera Singh',  email: 'meera@okas.one',  mobile: '6543210987', role: 'Member', status: 'Inactive' },
];

export const MOCK_FLOORS = [
  { id: 1, floor_name: 'Basement',     floor_type: 'Residential', floor_pos: -1, building_id: 'BLD001', floor_description: 'B1' },
  { id: 2, floor_name: 'Ground Floor', floor_type: 'Residential', floor_pos: 0,  building_id: 'BLD001', floor_description: 'GF' },
  { id: 3, floor_name: 'First Floor',  floor_type: 'Residential', floor_pos: 1,  building_id: 'BLD001', floor_description: '1F' },
  { id: 4, floor_name: 'Second Floor', floor_type: 'Residential', floor_pos: 2,  building_id: 'BLD001', floor_description: '2F' },
  { id: 5, floor_name: 'Ground Floor', floor_type: 'Commercial',  floor_pos: 0,  building_id: 'BLD002', floor_description: 'GF' },
  { id: 6, floor_name: 'First Floor',  floor_type: 'Commercial',  floor_pos: 1,  building_id: 'BLD002', floor_description: '1F' },
];

export const MOCK_ROOMS = [
  { id: 1,  room_name: 'Parking Area',      room_type: 'room', floor_id: 1, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 2,  room_name: 'Living Room',        room_type: 'room', floor_id: 2, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 3,  room_name: 'Kitchen',            room_type: 'room', floor_id: 2, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 4,  room_name: 'Dining Room',        room_type: 'room', floor_id: 2, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 5,  room_name: 'Master Bedroom',     room_type: 'room', floor_id: 3, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 6,  room_name: 'Guest Bedroom',      room_type: 'room', floor_id: 3, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 7,  room_name: 'Study Room',         room_type: 'room', floor_id: 3, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 8,  room_name: 'Kids Room',          room_type: 'room', floor_id: 4, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 9,  room_name: 'Home Theatre',       room_type: 'room', floor_id: 4, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 10, room_name: 'Reception',          room_type: 'room', floor_id: 5, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 11, room_name: 'Conference Room A',  room_type: 'room', floor_id: 5, room_image: null, subroom_id: null, zoneactive: 'true' },
  { id: 12, room_name: 'Open Work Area',     room_type: 'room', floor_id: 6, room_image: null, subroom_id: null, zoneactive: 'true' },
];

export const MOCK_LIGHTS = [
  { id: 1, device_id: 1, room_id: 2, domain: 'light', name: 'Main Ceiling',     address: '1/1/1', state_address: '1/1/2',  light_type: 'switch', platform: 'knx' },
  { id: 2, device_id: 1, room_id: 2, domain: 'light', name: 'Corner Lamp',      address: '1/1/3', state_address: '1/1/4',  light_type: 'dimmer', platform: 'knx', brightness_address: '1/1/5',  brightness_state_address: '1/1/6' },
  { id: 3, device_id: 1, room_id: 2, domain: 'light', name: 'TV Backlight',     address: '1/1/7', state_address: '1/1/8',  light_type: 'dimmer', platform: 'knx', brightness_address: '1/1/9',  brightness_state_address: '1/1/10' },
  { id: 4, device_id: 1, room_id: 2, domain: 'light', name: 'Entrance Spot',    address: '1/1/11',state_address: '1/1/12', light_type: 'switch', platform: 'knx' },
];
