export const DUMMY_PROJECTS = [
  {
    id: '1',
    name: 'Alfred Homes',
    address: 'Almas Tower, Dubai Marina',
    serialNumber: 'XJ47B9Q2',
    assignedSI: 'John Miller',
    installationDate: '12-05-2026',
    status: 'active',
  },
  {
    id: '2',
    name: 'Anderson',
    address: 'Jumeirah Beach Residence, Dubai',
    serialNumber: 'P9K3L8V1',
    assignedSI: 'Sarah Wilson',
    installationDate: '15-05-2026',
    status: 'in_progress',
  },
  {
    id: '3',
    name: 'David Ross',
    address: 'Business Bay, Dubai',
    serialNumber: 'Z8N4M6T5',
    assignedSI: 'Michael Brown',
    installationDate: '18-05-2026',
    status: 'active',
  },
  {
    id: '4',
    name: 'Sarah White',
    address: 'Downtown Dubai, Dubai',
    serialNumber: 'QW12ER45',
    assignedSI: 'Emily Davis',
    installationDate: '20-05-2026',
    status: 'active',
  },
  {
    id: '5',
    name: 'Kevin Adams',
    address: 'Dubai Silicon Oasis',
    serialNumber: 'TY67UI89',
    assignedSI: 'David Anderson',
    installationDate: '22-05-2026',
    status: 'active',
  },
  {
    id: '6',
    name: 'Ethan Carter',
    address: 'Dubai Internet City',
    serialNumber: 'AS90DF34',
    assignedSI: 'Jessica Taylor',
    installationDate: '25-05-2026',
    status: 'inactive',
  },
];
