import P from './permissions';
import { ROLES } from '../config/constants';

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [...Object.values(P)],
  [ROLES.DISTRIBUTOR]: [P.DASHBOARD_VIEW, P.PROJECTS_VIEW, P.PROJECTS_CREATE, P.PROJECTS_EDIT, P.SI_VIEW, P.SI_CREATE, P.SI_EDIT, P.PM_VIEW, P.PM_CREATE, P.PM_EDIT, P.USERS_VIEW, P.ORGS_VIEW, P.REPORTS_VIEW, P.NOTIFICATIONS_VIEW, P.SETTINGS_VIEW, P.BUILDINGS_VIEW, P.FLOORS_VIEW, P.ROOMS_VIEW, P.DEVICES_VIEW],
  [ROLES.SYSTEM_INTEGRATOR]: [P.DASHBOARD_VIEW, P.PROJECTS_VIEW, P.PROJECTS_CONFIGURE, P.PM_VIEW, P.USERS_VIEW, P.REPORTS_VIEW, P.NOTIFICATIONS_VIEW, P.SETTINGS_VIEW, P.BUILDINGS_VIEW, P.BUILDINGS_CREATE, P.BUILDINGS_EDIT, P.FLOORS_VIEW, P.FLOORS_CREATE, P.FLOORS_EDIT, P.ROOMS_VIEW, P.ROOMS_CREATE, P.ROOMS_EDIT, P.DEVICES_VIEW, P.DEVICES_CREATE, P.DEVICES_EDIT, P.DEVICES_CONFIGURE, P.AUTOMATION_VIEW, P.AUTOMATION_MANAGE, P.SCENES_VIEW, P.SCENES_MANAGE, P.SCENES_ACTIVATE, P.SCHEDULING_VIEW, P.SCHEDULING_MANAGE, P.MQTT_VIEW, P.MQTT_MANAGE, P.LAYOUT_VIEW, P.LAYOUT_MANAGE],
  [ROLES.PROJECT_MANAGER]: [P.DASHBOARD_VIEW, P.PROJECTS_VIEW, P.PROJECTS_CONFIGURE, P.USERS_VIEW, P.REPORTS_VIEW, P.REPORTS_EXPORT, P.NOTIFICATIONS_VIEW, P.SETTINGS_VIEW, P.BUILDINGS_VIEW, P.FLOORS_VIEW, P.ROOMS_VIEW, P.DEVICES_VIEW, P.AUTOMATION_VIEW, P.SCENES_VIEW, P.SCENES_ACTIVATE, P.SCHEDULING_VIEW, P.SCHEDULING_MANAGE, P.LAYOUT_VIEW],
  [ROLES.USER]: [P.DASHBOARD_VIEW, P.PROJECTS_VIEW, P.NOTIFICATIONS_VIEW, P.SETTINGS_VIEW, P.BUILDINGS_VIEW, P.FLOORS_VIEW, P.ROOMS_VIEW, P.DEVICES_VIEW, P.SCENES_VIEW, P.SCENES_ACTIVATE, P.SCHEDULING_VIEW],
};

export function getPermissionsForRole(role) { return ROLE_PERMISSIONS[role] || []; }
export function roleHasPermission(role, permission) { return getPermissionsForRole(role).includes(permission); }
export function roleHasAllPermissions(role, perms) { return perms.every((p) => roleHasPermission(role, p)); }
export function roleHasAnyPermission(role, perms) { return perms.some((p) => roleHasPermission(role, p)); }

export default ROLE_PERMISSIONS;
